### ISSUE TITLE
Uncaught TypeError: this.editor.verticallyScrollable is not a function

### ISSUE THREAD

**Issue by averrin** [smashwilson/merge-conflicts#187]
[Enter steps to reproduce below:]

1. Just open

**in beta channel**

**Atom Version**: 1.1.0-beta1
**System**: Ubuntu 15.10
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.6

### Stack Trace

Uncaught TypeError: this.editor.verticallyScrollable is not a function

```
At /home/user/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:36

TypeError: this.editor.verticallyScrollable is not a function
  at SideView.CoveringView.attached (/home/user/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:18:32)
  at SideView.attached (/home/user/.atom/packages/merge-conflicts/lib/view/side-view.coffee:26:5)
  at space-pen-div.View.element.attached (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/home/user/.atom/packages/python-iresolve/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:51:55)
  at OverlayManager.module.exports.OverlayManager.renderOverlay (/usr/share/atom-beta/resources/app.asar/src/overlay-manager.js:77:21)
  at OverlayManager.module.exports.OverlayManager.render (/usr/share/atom-beta/resources/app.asar/src/overlay-manager.js:17:16)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:236:15)
  at /usr/share/atom-beta/resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom-beta/resources/app.asar/src/view-registry.js:174:9)
  at /usr/share/atom-beta/resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
  2x -0:19.2.0 tidy-tabs:remove-stale-tabs (atom-text-editor.editor.vim-mode.normal-mode)
     -0:07.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-accents-ui)
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 merge-conflicts:detect (atom-text-editor.editor.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "web-browser",
      "tool-bar-main",
      "atom-jade",
      "spell-check",
      "seti-icons",
      "atom-color-highlight",
      "local-history",
      "project-view",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "linter-tidy",
      "deprecation-cop",
      "linter-python-pyflakes",
      "opened-files",
      "hyperclick",
      "symbol-gen",
      "symbols-view",
      "symbols-tree-view"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.4.33
accents-ui, v1.0.0
atom-ctags, v4.3.0
atom-jinja2, v0.5.0
auto-reveal-in-sidebar, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-python, v0.8.2
color-picker, v2.0.13
color-picker-service, v0.0.1
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
emmet, v2.3.13
file-icons, v1.6.11
foldername-tabs, v0.1.5
git-hide, v0.1.2
github-notifications, v0.1.1
javascript-snippets, v1.0.0
language-diff, v0.3.1
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-nunjucks, v2.0.0
last-cursor-position, v0.9.0
linter, v1.9.0
linter-eslint, v3.1.1
linter-jscs, v3.1.2
linter-jshint, v1.2.1
linter-pep8, v1.0.1
linter-pylama, v0.2.0
merge-conflicts, v1.3.6
minimap, v4.15.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
nerd-treeview, v0.3.1
pigments, v0.18.0
python-iresolve, v0.0.3
python-tools, v0.6.5
remember-file-positions, v0.2.0
swackets, v0.5.3
sync-settings, v0.6.0
tidy-tabs, v0.3.0
time-status, v1.1.0
underline-trailing-whitespace, v1.4.0
vim-mode, v0.61.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by ssundkvist** [comment]
Getting the same error in Atom version 1.1.0

**Comment by msdark** [comment]
me too.. same version

**Comment by gzamboni** [comment]
same error here. 

[Enter steps to reproduce below:]

1. Open Git Merge Conflicts List
2. Open a conflict

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.6


### Stack Trace

Uncaught TypeError: this.editor.verticallyScrollable is not a function

```
At /Users/zamboni/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:36

TypeError: this.editor.verticallyScrollable is not a function
  at SideView.CoveringView.attached (/Users/zamboni/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:18:32)
  at SideView.attached (/Users/zamboni/.atom/packages/merge-conflicts/lib/view/side-view.coffee:26:5)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at OverlayManager.module.exports.OverlayManager.renderOverlay (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:77:21)
  at OverlayManager.module.exports.OverlayManager.render (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:17:16)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:236:15)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:278:21)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:929:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:131:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:247:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:311:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:474:16
  at process._tickCallback (node.js:365:9)

```

### Commands

```
     -0:22.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.2.0 merge-conflicts:detect (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "merge-conflicts": {
    "gitPath": "/usr/bin/git"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-boilerplate-snippets, v0.3.1
atom-trello, v0.3.0
build, v0.48.0
build-gulp, v0.2.0
file-icons, v1.6.11
language-jade, v0.6.2
merge-conflicts, v1.3.6
minimap, v4.15.2
project-manager, v2.6.5
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by rthijssen** [comment]
Yep same error here

**Comment by Victoor** [comment]
Same here :/

**Comment by cometeer** [comment]
here too!

**Comment by xtrasmal** [comment]
Here too. Never used the plugin before.

**Comment by smashwilson** [comment]
Yeah, looks like I was relying on a private method that was removed. I'll see what I can do :wrench:

**Comment by smashwilson** [comment]
Okay, this'll be fixed by the next release, modulo some unfortunate visual artifacts:

![screen shot 2015-11-02 at 2 34 19 pm](https://cloud.githubusercontent.com/assets/17565/10892437/66ea3d56-8171-11e5-8dca-d3e29ab08c6e.jpeg)

But at least it won't :boom: as soon as it's launched, so, progress!

**Comment by arbourd** [comment]
Thanks for the fix today @smashwilson

**Comment by nanorepublica** [comment]
Hi still getting this issue

[Enter steps to reproduce below:]

1. run the command from the control palette
2. getting multiples of everything (list of files bits in each file)

<img width="682" alt="screen shot 2015-11-09 at 15 04 27" src="https://cloud.githubusercontent.com/assets/1997940/11036967/3b557a66-86f3-11e5-9dd2-14d213e7e74d.png">


**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7


### Stack Trace

Uncaught TypeError: this.editor.verticallyScrollable is not a function

```
At /Users/andrew/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:18

TypeError: this.editor.verticallyScrollable is not a function
  at SideView.CoveringView.attached (/Users/andrew/.atom/packages/merge-conflicts/lib/view/covering-view.coffee:18:31)
  at SideView.attached (/Users/andrew/.atom/packages/merge-conflicts/lib/view/side-view.coffee:26:5)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Users/andrew/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:51:55)
  at OverlayManager.module.exports.OverlayManager.renderOverlay (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:77:21)
  at OverlayManager.module.exports.OverlayManager.render (/Applications/Atom.app/Contents/Resources/app.asar/src/overlay-manager.js:17:16)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:236:15)
  at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:278:21)
  at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:929:16)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:131:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:247:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:311:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:474:16
  at process._tickCallback (node.js:365:9)

```

### Commands

```
     -6:01.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:01.4.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -6:01.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:43.8.0 core:select-all (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:41.1.0 core:copy (atom-text-editor.editor.is-focused)
     -2:34 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:32.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:32 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:32 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:02.8.0 settings-view:open (atom-pane.pane.active)
  2x -1:08.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.8.0 command-palette:toggle (atom-workspace.workspace.theme-monokai.theme-seti-ui.scrollbars-visible-when-scrolling.find-visible)
     -0:38.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 merge-conflicts:detect (atom-workspace.workspace.theme-monokai.theme-seti-ui.scrollbars-visible-when-scrolling.find-visible)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "syntax-tree",
      "about"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "projectHome": "/Users/amiller"
  },
  "merge-conflicts": {
    "gitPath": "/usr/bin/git"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-cli-diff, v1.1.0
atom-django, v0.3.0
atom-jinja2, v0.5.0
atom-justify, v0.4.1
autocomplete-paths, v1.0.2
browser-plus, v0.0.54
build, v0.48.0
color-picker, v2.0.13
command-logger, v0.23.0
cucumber, v0.5.0
django-templates, v0.5.0
editor-stats, v0.17.0
editorconfig, v1.2.2
gist-it, v0.8.0
git-blame, v0.4.7
git-go, v1.0.1
git-grep, v0.9.0
git-log, v0.4.1
git-plus, v5.5.6
go-plus, v3.5.1
inline-autocomplete, v1.1.0
jsonlint, v1.1.2
language-django, v0.1.1
language-docker, v1.1.3
language-ini, v1.14.0
language-puppet, v0.15.0
language-python-django-templates, v0.1.0
language-rst, v0.2.1-0
linter, v1.10.0
linter-pep8, v1.0.1
linter-puppet, v1.0.0
linter-pylint, v1.0.3
merge-conflicts, v1.3.7
minimap, v4.16.0
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
monokai, v0.18.0
open-recent, v4.0.1
pretty-json, v0.4.1
project-colorize, v0.2.0
project-manager, v2.6.5
set-syntax, v0.3.0
seti-ui, v0.8.1
sort-lines, v0.12.0
svg-preview, v0.6.1
sync-settings, v0.6.0
travis-ci-status, v0.18.0
wordcount, v2.4.0
youtube-pane, v1.5.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
@nanorepublica Have you restarted Atom since the merge-conflicts upgrade? That stack trace is still referencing source that doesn't exist any more.

**Comment by nanorepublica** [comment]
I probably hadn't, have just restarted but I no longer have any conflicts to test, feel free to close this again  :)

**Comment by smashwilson** [comment]
:+1:

Thanks for the report :smile:

**Comment by gzamboni** [comment]
Working fine here! thanks @smashwilson!!!! :clap:
